// Code Mostly generated by xgen. DO NOT EDIT.

package schema

import (
	"encoding/xml"
)

// Executable ...
type Executable *ExecutableTypePackage

// Property ...
type Property struct {
	NameAttr *string `xml:"Name,attr"`
	*PropertyElementBaseType
}

// ExecutableTypePackage ...
type ExecutableTypePackage struct {
	ExecutableTypeAttr   *string                          `xml:"ExecutableType,attr"`
	Property             []*Property                      `xml:"Property"`
	ConnectionManagers   *ConnectionManagersType          `xml:"ConnectionManagers"`
	Configuration        []*ConfigurationType             `xml:"Configuration"`
	LogProvider          []*LogProviderType               `xml:"LogProvider"`
	Variables            *VariablesType                   `xml:"Variables"`
	LoggingOptions       *LoggingOptionsType              `xml:"LoggingOptions"`
	PropertyExpression   []*PropertyExpressionElementType `xml:"PropertyExpression"`
	Executable           []*AnyNonPackageExecutableType   `xml:"Executables>Executable"`
	PrecedenceConstraint []*PrecedenceConstraintType      `xml:"PrecedenceConstraint"`
	EventHandler         []*EventHandlerType              `xml:"EventHandler"`
	PackageVariable      []*PackageVariableType           `xml:"PackageVariable"`
}

// AnyNonPackageExecutableType ...
type AnyNonPackageExecutableType struct {
	RefIdAttr              *string                          `xml:"refId,attr"`
	ExecutableTypeAttr     string                           `xml:"ExecutableType,attr"`
	ObjectNameAttr         *string                          `xml:"ObjectName,attr"`
	CreationNameAttr       *string                          `xml:"CreationName,attr"`
	DTSIDAttr              *string                          `xml:"DTSID,attr"`
	ThreadHintAttr         *int                             `xml:"ThreadHint,attr"`
	ForEachEnumerator      *ForEachEnumeratorType           `xml:"ForEachEnumerator"`
	Property               []*Property                      `xml:"Property"`
	Variable               []*VariableType                  `xml:"Variable"`
	LoggingOptions         *LoggingOptionsType              `xml:"LoggingOptions"`
	PropertyExpression     []*PropertyExpressionElementType `xml:"PropertyExpression"`
	Executable             []*AnyNonPackageExecutableType   `xml:"Executable"`
	PrecedenceConstraint   []*PrecedenceConstraintType      `xml:"PrecedenceConstraint"`
	ForEachVariableMapping []*ForEachVariableMappingType    `xml:"ForEachVariableMapping"`
	EventHandler           []*EventHandlerType              `xml:"EventHandler"`
	ObjectData             *ExecutableObjectDataType        `xml:"ObjectData"`
}

// PackageVariableType ...
type PackageVariableType struct {
	Property           []*Property                      `xml:"Property"`
	PropertyExpression []*PropertyExpressionElementType `xml:"PropertyExpression"`
}

// ConfigurationType ...
type ConfigurationType struct {
	Property           []*Property                      `xml:"Property"`
	PropertyExpression []*PropertyExpressionElementType `xml:"PropertyExpression"`
}

// LogProviderType ...
type LogProviderType struct {
	Property           []*Property                      `xml:"Property"`
	PropertyExpression []*PropertyExpressionElementType `xml:"PropertyExpression"`
	ObjectData         *LogProviderObjectDataType       `xml:"ObjectData"`
}

// ConnectionManagersType ...
type ConnectionManagersType struct {
	ConnectionManager []*ConnectionManagerType `xml:"ConnectionManager"`
}

// ConnectionManagerType ...
type ConnectionManagerType struct {
	RefIdAttr          *string                          `xml:"refId,attr"`
	CreationNameAttr   *string                          `xml:"CreationName,attr"`
	DTSIDAttr          *string                          `xml:"DTSID,attr"`
	ObjectNameAttr     *string                          `xml:"ObjectName,attr"`
	Property           []*Property                      `xml:"Property"`
	PropertyExpression []*PropertyExpressionElementType `xml:"PropertyExpression"`
	ObjectData         *ConnectionManagerObjectDataType `xml:"ObjectData"`
}

// PrecedenceConstraintType ...
type PrecedenceConstraintType struct {
	Property           []*Property                                    `xml:"Property"`
	PropertyExpression []*PropertyExpressionElementType               `xml:"PropertyExpression"`
	Executable         []*PrecedenceConstraintExecutableReferenceType `xml:"Executable"`
}

// PrecedenceConstraintExecutableReferenceType ...
type PrecedenceConstraintExecutableReferenceType struct {
	IDREFAttr  *string `xml:"IDREF,attr"`
	IsFromAttr *int    `xml:"IsFrom,attr"`
}

// LoggingOptionsType ...
type LoggingOptionsType struct {
	Property            []*LoggingOptionsPropertyElementType `xml:"Property"`
	PropertyExpression  []*PropertyExpressionElementType     `xml:"PropertyExpression"`
	SelectedLogProvider []*SelectedLogProviderType           `xml:"SelectedLogProvider"`
}

// LoggingOptionsPropertyElementType ...
type LoggingOptionsPropertyElementType struct {
	NameAttr      string      `xml:"Name,attr"`
	DataTypeAttr  *int        `xml:"DataType,attr"`
	EventNameAttr *string     `xml:"EventName,attr"`
	Property      []*Property `xml:"Property"`
}

// SelectedLogProviderType ...
type SelectedLogProviderType struct {
	InstanceIDAttr *string `xml:"InstanceID,attr"`
}

// VariableValue ...
type VariableValue struct {
	DataTypeAttr    *int    `xml:"DataType,attr"`
	DataSubTypeAttr *string `xml:"DataSubType,attr"`
	Value           string  `xml:",chardata"`
}

// VariablesType ...
type VariablesType struct {
	Variable []*VariableType `xml:"Variable"`
}

// VariableType ...
type VariableType struct {
	NamespaceAttr      *string                          `xml:"Namespace,attr"`
	ObjectNameAttr     *string                          `xml:"ObjectName,attr"`
	Property           []*Property                      `xml:"Property"`
	PropertyExpression []*PropertyExpressionElementType `xml:"PropertyExpression"`
	VariableValue      *VariableValue                   `xml:"VariableValue"`
}

// EventHandlerType ...
type EventHandlerType struct {
	Property             []*Property                      `xml:"Property"`
	PropertyExpression   []*PropertyExpressionElementType `xml:"PropertyExpression"`
	Variable             []*VariableType                  `xml:"Variable"`
	LoggingOptions       *LoggingOptionsType              `xml:"LoggingOptions"`
	Executable           []*AnyNonPackageExecutableType   `xml:"Executable"`
	PrecedenceConstraint []*PrecedenceConstraintType      `xml:"PrecedenceConstraint"`
}

// ForEachEnumeratorType ...
type ForEachEnumeratorType struct {
	Property           []*Property                      `xml:"Property"`
	PropertyExpression []*PropertyExpressionElementType `xml:"PropertyExpression"`
	ObjectData         *ForEachEnumeratorObjectDataType `xml:"ObjectData"`
}

// ForEachVariableMappingType ...
type ForEachVariableMappingType struct {
	Property           []*Property                      `xml:"Property"`
	PropertyExpression []*PropertyExpressionElementType `xml:"PropertyExpression"`
}

// ExecutableObjectDataType ...
type ExecutableObjectDataType struct {
	Pipeline                               *PipelineObjectDataType                         `xml:"pipeline"`
	ActiveXScriptTaskActiveXScriptTaskData *ActiveXScriptTaskDataType                      `xml:"ActiveXScriptTask:ActiveXScriptTaskData"`
	ASDdlData                              *ASDdlDataObjectDataType                        `xml:"ASDdlData"`
	ASProcessingData                       *ASProcessingDataObjectDataType                 `xml:"ASProcessingData"`
	BulkInsertTaskBulkInsertTaskData       *BulkInsertTaskDataType                         `xml:"BulkInsertTask:BulkInsertTaskData"`
	DMQueryTaskData                        *DMQueryTaskDataObjectDataType                  `xml:"DMQueryTaskData"`
	DataProfilingTaskData                  *DataProfilingTaskDataObjectDataType            `xml:"DataProfilingTaskData"`
	Exec80PackageTaskExec80PackageTaskData *Exec80PackageTaskType                          `xml:"Exec80PackageTask:Exec80PackageTaskData"`
	ExecutePackageTask                     *ExecutePackageTaskObjectDataType               `xml:"ExecutePackageTask"`
	ExecuteProcessData                     *ExecuteProcessDataObjectDataType               `xml:"ExecuteProcessData"`
	SQLTaskSqlTaskData                     *SqlTaskDataType                                `xml:"SQLTask:SqlTaskData"`
	FileSystemData                         *FileSystemDataObjectDataType                   `xml:"FileSystemData"`
	FtpData                                *FtpDataObjectDataType                          `xml:"FtpData"`
	MessageQueueTaskMessageQueueTaskData   *MessageQueueTaskType                           `xml:"MessageQueueTask:MessageQueueTaskData"`
	ScriptProject                          *ScriptProjectObjectDataType                    `xml:"ScriptProject"`
	SendMailTaskSendMailTaskData           *SendMailTaskType                               `xml:"SendMailTask:SendMailTaskData"`
	TransferDatabasesTaskData              *TransferDatabasesTaskDataObjectDataType        `xml:"TransferDatabasesTaskData"`
	TransferErrorMessagesTaskData          *TransferErrorMessagesTaskDataObjectDataType    `xml:"TransferErrorMessagesTaskData"`
	TransferJobsTaskData                   *TransferJobsTaskDataObjectDataType             `xml:"TransferJobsTaskData"`
	TransferLoginsTaskData                 *TransferLoginsTaskDataObjectDataType           `xml:"TransferLoginsTaskData"`
	TransferStoredProceduresTaskData       *TransferStoredProceduresTaskDataObjectDataType `xml:"TransferStoredProceduresTaskData"`
	TransferSqlServerObjectsTaskData       *TransferSqlServerObjectsTaskDataObjectDataType `xml:"TransferSqlServerObjectsTaskData"`
	WSTaskWebServiceTaskData               *WSTaskDataType                                 `xml:"WSTask:WebServiceTaskData"`
	WMIDRTaskData                          *WMIDRTaskDataObjectDataType                    `xml:"WMIDRTaskData"`
	WMIEWTaskData                          *WMIEWTaskDataObjectDataType                    `xml:"WMIEWTaskData"`
	XMLTaskData                            *XMLTaskDataObjectDataType                      `xml:"XMLTaskData"`
	InnerObject                            *InnerObjectObjectDataType                      `xml:"InnerObject"`
	InnerXML                               string                                          `xml:",innerxml"`
}

// ASDdlDataObjectDataType ...
type ASDdlDataObjectDataType struct {
	ConnectionNameAttr *string `xml:"ConnectionName,attr"`
	SourceTypeAttr     *string `xml:"SourceType,attr"`
	SourceAttr         *string `xml:"Source,attr"`
}

// ASProcessingDataObjectDataType ...
type ASProcessingDataObjectDataType struct {
	ConnectionNameAttr     *string `xml:"ConnectionName,attr"`
	ProcessingCommandsAttr *string `xml:"ProcessingCommands,attr"`
}

// DMQueryTaskDataObjectDataType ...
type DMQueryTaskDataObjectDataType struct {
	InputConnectionAttr       *string                              `xml:"InputConnection,attr"`
	OutputConnectionAttr      *string                              `xml:"OutputConnection,attr"`
	ModelStructureNameAttr    *string                              `xml:"ModelStructureName,attr"`
	ModelNameAttr             *string                              `xml:"ModelName,attr"`
	OverwriteOutputTableAttr  *string                              `xml:"OverwriteOutputTable,attr"`
	OutputTableNameAttr       *string                              `xml:"OutputTableName,attr"`
	QueryString               *DMQueryTaskQueryStringContainerType `xml:"QueryString"`
	QueryBuilderQueryString   *DMQueryTaskQueryStringContainerType `xml:"QueryBuilderQueryString"`
	QueryBuilderSpecification *DMQueryBuilderSpecificationType     `xml:"QueryBuilderSpecification"`
}

// DMQueryTaskQueryStringContainerType ...
type DMQueryTaskQueryStringContainerType struct {
	SensitiveAttr *bool  `xml:"Sensitive,attr"`
	EncryptedAttr *bool  `xml:"Encrypted,attr"`
	Value         string `xml:",chardata"`
}

// DMQueryBuilderSpecificationType ...
type DMQueryBuilderSpecificationType struct {
	SensitiveAttr *bool `xml:"Sensitive,attr"`
	EncryptedAttr *bool `xml:"Encrypted,attr"`
}

// DataProfilingTaskDataObjectDataType ...
type DataProfilingTaskDataObjectDataType struct {
	DestinationTypeAttr      *string `xml:"DestinationType,attr"`
	DestinationAttr          *string `xml:"Destination,attr"`
	OverwriteDestinationAttr *string `xml:"OverwriteDestination,attr"`
	ProfileInput             string  `xml:"ProfileInput"`
}

// DestinationTypeEnum ...
type DestinationTypeEnum string

// ExecutePackageTaskObjectDataType ...
type ExecutePackageTaskObjectDataType struct {
	ExecuteOutOfProcess interface{}          `xml:"ExecuteOutOfProcess"`
	PackageName         string               `xml:"PackageName"`
	PackagePassword     *PasswordElementType `xml:"PackagePassword"`
	PackageID           string               `xml:"PackageID"`
	VersionID           string               `xml:"VersionID"`
	Connection          string               `xml:"Connection"`
}

// ExecuteProcessDataObjectDataType ...
type ExecuteProcessDataObjectDataType struct {
	ExecutableAttr                            *string `xml:"Executable,attr"`
	RequireFullFileNameAttr                   *string `xml:"RequireFullFileName,attr"`
	ArgumentsAttr                             *string `xml:"Arguments,attr"`
	WorkingDirectoryAttr                      *string `xml:"WorkingDirectory,attr"`
	TimeOutAttr                               *int    `xml:"TimeOut,attr"`
	FailTaskIfReturnCodeIsNotSuccessValueAttr *string `xml:"FailTaskIfReturnCodeIsNotSuccessValue,attr"`
	SuccessValueAttr                          *int    `xml:"SuccessValue,attr"`
	TerminateAfterTimeoutAttr                 *string `xml:"TerminateAfterTimeout,attr"`
	StandardInputVariableAttr                 *string `xml:"StandardInputVariable,attr"`
	StandardOutputVariableAttr                *string `xml:"StandardOutputVariable,attr"`
	StandardErrorVariableAttr                 *string `xml:"StandardErrorVariable,attr"`
	WindowStyleAttr                           *string `xml:"WindowStyle,attr"`
}

// WindowStyleEnum ...
type WindowStyleEnum string

// FileSystemDataObjectDataType ...
type FileSystemDataObjectDataType struct {
	TaskOperationTypeAttr         *string `xml:"TaskOperationType,attr"`
	OperationNameAttr             *string `xml:"OperationName,attr"`
	TaskOverwriteDestFileAttr     *string `xml:"TaskOverwriteDestFile,attr"`
	TaskSourcePathAttr            *string `xml:"TaskSourcePath,attr"`
	TaskIsSourceVariableAttr      *string `xml:"TaskIsSourceVariable,attr"`
	TaskDestinationPathAttr       *string `xml:"TaskDestinationPath,attr"`
	TaskIsDestinationVariableAttr *string `xml:"TaskIsDestinationVariable,attr"`
	TaskFileAttributesAttr        *string `xml:"TaskFileAttributes,attr"`
}

// FtpDataObjectDataType ...
type FtpDataObjectDataType struct {
	ConnectionNameAttr      *string `xml:"ConnectionName,attr"`
	StopOnFailureAttr       *string `xml:"StopOnFailure,attr"`
	TaskOperationTypeAttr   *string `xml:"TaskOperationType,attr"`
	TaskOperationNameAttr   *string `xml:"TaskOperationName,attr"`
	TaskIsLocalPathVarAttr  *string `xml:"TaskIsLocalPathVar,attr"`
	TaskLocalPathAttr       *string `xml:"TaskLocalPath,attr"`
	TaskIsRemotePathVarAttr *string `xml:"TaskIsRemotePathVar,attr"`
	TaskRemotePathAttr      *string `xml:"TaskRemotePath,attr"`
	TaskOverwriteDestAttr   *string `xml:"TaskOverwriteDest,attr"`
	TaskTransferAsciiAttr   *string `xml:"TaskTransferAscii,attr"`
}

// FtpDataTaskOperationTypeEnum ...
type FtpDataTaskOperationTypeEnum string

// ScriptProjectObjectDataType ...
type ScriptProjectObjectDataType struct {
	NameAttr               *string                         `xml:"Name,attr"`
	VSTAMajorVersionAttr   *int                            `xml:"VSTAMajorVersion,attr"`
	VSTAMinorVersionAttr   *int                            `xml:"VSTAMinorVersion,attr"`
	LanguageAttr           *string                         `xml:"Language,attr"`
	EntryPointAttr         *string                         `xml:"EntryPoint,attr"`
	ReadOnlyVariablesAttr  *string                         `xml:"ReadOnlyVariables,attr"`
	ReadWriteVariablesAttr *string                         `xml:"ReadWriteVariables,attr"`
	ProjectItem            []*ScriptProjectProjectItemType `xml:"ProjectItem"`
	BinaryItem             *ScriptProjectBinaryItemType    `xml:"BinaryItem"`
	Breakpoint             []*ScriptProjectBreakpointType  `xml:"Breakpoint"`
}

// ScriptProjectProjectItemType ...
type ScriptProjectProjectItemType struct {
	NameAttr *string `xml:"Name,attr"`
	Value    string  `xml:",chardata"`
}

// ScriptProjectBinaryItemType ...
type ScriptProjectBinaryItemType struct {
	NameAttr *string `xml:"Name,attr"`
	Value    string  `xml:",chardata"`
}

// ScriptProjectBreakpointType ...
type ScriptProjectBreakpointType struct {
	NameAttr          *string `xml:"Name,attr"`
	EnabledAttr       *string `xml:"Enabled,attr"`
	FunctionAttr      *string `xml:"Function,attr"`
	FileAttr          *string `xml:"File,attr"`
	LineAttr          *int    `xml:"Line,attr"`
	ColumnAttr        *int    `xml:"Column,attr"`
	ConditionAttr     *string `xml:"Condition,attr"`
	ConditionTypeAttr *int    `xml:"ConditionType,attr"`
	LanguageAttr      *string `xml:"Language,attr"`
	HitCountAttr      *int    `xml:"HitCount,attr"`
	HitCountTypeAttr  *int    `xml:"HitCountType,attr"`
}

// ScriptProjectLanguageEnum ...
type ScriptProjectLanguageEnum string

// ScriptProjectHitCountTypeEnum ...
type ScriptProjectHitCountTypeEnum int

// ScriptProjectConditionTypeEnum ...
type ScriptProjectConditionTypeEnum int

// TransferDatabasesTaskDataObjectDataType ...
type TransferDatabasesTaskDataObjectDataType struct {
	SrcConnAttr       *string `xml:"SrcConn,attr"`
	DestConnAttr      *string `xml:"DestConn,attr"`
	ActionAttr        *int    `xml:"Action,attr"`
	MethodAttr        *int    `xml:"Method,attr"`
	SrcDBNameAttr     *string `xml:"SrcDBName,attr"`
	ReattachSrcDBAttr *bool   `xml:"ReattachSrcDB,attr"`
	SrcDBFilesAttr    *string `xml:"SrcDBFiles,attr"`
	DestDBNameAttr    *string `xml:"DestDBName,attr"`
	DestDBFilesAttr   *string `xml:"DestDBFiles,attr"`
	DestOverwriteAttr *bool   `xml:"DestOverwrite,attr"`
}

// TransferDatabaseTaskActionEnum ...
type TransferDatabaseTaskActionEnum int

// TransferDatabaseTaskMethodEnum ...
type TransferDatabaseTaskMethodEnum int

// TransferErrorMessagesTaskDataObjectDataType ...
type TransferErrorMessagesTaskDataObjectDataType struct {
	TransferAllErrorMessagesAttr  *bool   `xml:"TransferAllErrorMessages,attr"`
	ErrorMessagesListAttr         *string `xml:"ErrorMessagesList,attr"`
	ErrorMessageLanguagesListAttr *string `xml:"ErrorMessageLanguagesList,attr"`
	IfObjectExistsAttr            *string `xml:"IfObjectExists,attr"`
	SourceConnectionAttr          *string `xml:"SourceConnection,attr"`
	DestinationConnectionAttr     *string `xml:"DestinationConnection,attr"`
}

// IfObjectExistsEnum ...
type IfObjectExistsEnum string

// TransferJobsTaskDataObjectDataType ...
type TransferJobsTaskDataObjectDataType struct {
	TransferAllJobsAttr         *bool   `xml:"TransferAllJobs,attr"`
	JobsListAttr                *string `xml:"JobsList,attr"`
	IfObjectExistsAttr          *string `xml:"IfObjectExists,attr"`
	EnableJobsAtDestinationAttr *bool   `xml:"EnableJobsAtDestination,attr"`
	SourceConnectionAttr        *string `xml:"SourceConnection,attr"`
	DestinationConnectionAttr   *string `xml:"DestinationConnection,attr"`
}

// TransferLoginsTaskDataObjectDataType ...
type TransferLoginsTaskDataObjectDataType struct {
	LoginsToTransferAttr      *string `xml:"LoginsToTransfer,attr"`
	CopySidsAttr              *bool   `xml:"CopySids,attr"`
	LoginListAttr             *string `xml:"LoginList,attr"`
	IfObjectExistsAttr        *string `xml:"IfObjectExists,attr"`
	SourceConnectionAttr      *string `xml:"SourceConnection,attr"`
	DestinationConnectionAttr *string `xml:"DestinationConnection,attr"`
	DatabasesListAttr         *string `xml:"DatabasesList,attr"`
}

// TransferLoginsTaskLoginsToTransferEnum ...
type TransferLoginsTaskLoginsToTransferEnum string

// TransferStoredProceduresTaskDataObjectDataType ...
type TransferStoredProceduresTaskDataObjectDataType struct {
	TransferAllStoredProceduresAttr *bool   `xml:"TransferAllStoredProcedures,attr"`
	StoredProceduresListAttr        *string `xml:"StoredProceduresList,attr"`
	IfObjectExistsAttr              *string `xml:"IfObjectExists,attr"`
	SourceConnectionAttr            *string `xml:"SourceConnection,attr"`
	MDestinationConnectionIDAttr    *string `xml:"m_DestinationConnectionID,attr"`
}

// TransferSqlServerObjectsTaskDataObjectDataType ...
type TransferSqlServerObjectsTaskDataObjectDataType struct {
	SourceConnectionAttr             *string `xml:"SourceConnection,attr"`
	DestinationConnectionAttr        *string `xml:"DestinationConnection,attr"`
	SourceDatabaseAttr               *string `xml:"SourceDatabase,attr"`
	DestinationDatabaseAttr          *string `xml:"DestinationDatabase,attr"`
	CopyAllObjectsAttr               *bool   `xml:"CopyAllObjects,attr"`
	CopyAllRulesAttr                 *bool   `xml:"CopyAllRules,attr"`
	CopyAllTablesAttr                *bool   `xml:"CopyAllTables,attr"`
	CopyAllViewsAttr                 *bool   `xml:"CopyAllViews,attr"`
	CopyAllStoredProceduresAttr      *bool   `xml:"CopyAllStoredProcedures,attr"`
	CopyAllUserDefinedFunctionsAttr  *bool   `xml:"CopyAllUserDefinedFunctions,attr"`
	CopyAllDefaultsAttr              *bool   `xml:"CopyAllDefaults,attr"`
	CopyAllUserDefinedDataTypesAttr  *bool   `xml:"CopyAllUserDefinedDataTypes,attr"`
	CopyAllPartitionFunctionsAttr    *bool   `xml:"CopyAllPartitionFunctions,attr"`
	CopyAllPartitionSchemesAttr      *bool   `xml:"CopyAllPartitionSchemes,attr"`
	CopyAllSchemasAttr               *bool   `xml:"CopyAllSchemas,attr"`
	CopyAllSqlAssembliesAttr         *bool   `xml:"CopyAllSqlAssemblies,attr"`
	CopyAllUserDefinedAggregatesAttr *bool   `xml:"CopyAllUserDefinedAggregates,attr"`
	CopyAllUserDefinedTypesAttr      *bool   `xml:"CopyAllUserDefinedTypes,attr"`
	CopyAllXmlSchemaCollectionsAttr  *bool   `xml:"CopyAllXmlSchemaCollections,attr"`
	LoginsListAttr                   *string `xml:"LoginsList,attr"`
	UsersListAttr                    *string `xml:"UsersList,attr"`
	RulesListAttr                    *string `xml:"RulesList,attr"`
	TablesListAttr                   *string `xml:"TablesList,attr"`
	ViewsListAttr                    *string `xml:"ViewsList,attr"`
	StoredProceduresListAttr         *string `xml:"StoredProceduresList,attr"`
	UserDefinedFunctionsListAttr     *string `xml:"UserDefinedFunctionsList,attr"`
	DefaultsListAttr                 *string `xml:"DefaultsList,attr"`
	UserDefinedDataTypesListAttr     *string `xml:"UserDefinedDataTypesList,attr"`
	PartitionFunctionsListAttr       *string `xml:"PartitionFunctionsList,attr"`
	PartitionSchemesListAttr         *string `xml:"PartitionSchemesList,attr"`
	SchemasListAttr                  *string `xml:"SchemasList,attr"`
	SqlAssembliesListAttr            *string `xml:"SqlAssembliesList,attr"`
	UserDefinedAggregatesListAttr    *string `xml:"UserDefinedAggregatesList,attr"`
	UserDefinedTypesListAttr         *string `xml:"UserDefinedTypesList,attr"`
	XmlSchemaCollectionsListAttr     *string `xml:"XmlSchemaCollectionsList,attr"`
	DropObjectsFirstAttr             *bool   `xml:"DropObjectsFirst,attr"`
	IncludeDependentObjectsAttr      *bool   `xml:"IncludeDependentObjects,attr"`
	IncludeExtendedPropertiesAttr    *bool   `xml:"IncludeExtendedProperties,attr"`
	CopyDataAttr                     *bool   `xml:"CopyData,attr"`
	ExistingDataAttr                 *string `xml:"ExistingData,attr"`
	CopySchemaAttr                   *bool   `xml:"CopySchema,attr"`
	UseCollationAttr                 *bool   `xml:"UseCollation,attr"`
	CopyDatabaseUsersAttr            *bool   `xml:"CopyDatabaseUsers,attr"`
	CopyDatabaseRolesAttr            *bool   `xml:"CopyDatabaseRoles,attr"`
	CopySqlServerLoginsAttr          *bool   `xml:"CopySqlServerLogins,attr"`
	CopyObjectLevelPermissionsAttr   *bool   `xml:"CopyObjectLevelPermissions,attr"`
	CopyIndexesAttr                  *bool   `xml:"CopyIndexes,attr"`
	CopyTriggersAttr                 *bool   `xml:"CopyTriggers,attr"`
	CopyFullTextIndexesAttr          *bool   `xml:"CopyFullTextIndexes,attr"`
	CopyPrimaryKeysAttr              *bool   `xml:"CopyPrimaryKeys,attr"`
	CopyForeignKeysAttr              *bool   `xml:"CopyForeignKeys,attr"`
	GenerateScriptsInUnicodeAttr     *bool   `xml:"GenerateScriptsInUnicode,attr"`
	SourceTranslateCharAttr          *bool   `xml:"SourceTranslateChar,attr"`
	DestinationTranslateCharAttr     *bool   `xml:"DestinationTranslateChar,attr"`
	CopyAllDRIObjectsAttr            *bool   `xml:"CopyAllDRIObjects,attr"`
}

// TransferSqlServerObjectsTaskExistingDataEnum ...
type TransferSqlServerObjectsTaskExistingDataEnum string

// WMIDRTaskDataObjectDataType ...
type WMIDRTaskDataObjectDataType struct {
	WQLQuerySourceTypeAttr   *string `xml:"WQLQuerySourceType,attr"`
	WQLQuerySourceAttr       *string `xml:"WQLQuerySource,attr"`
	DestinationTypeAttr      *string `xml:"DestinationType,attr"`
	DestinationAttr          *string `xml:"Destination,attr"`
	OverwriteDestinationAttr *string `xml:"OverwriteDestination,attr"`
	OutputTypeAttr           *string `xml:"OutputType,attr"`
	WMIConnectionNameAttr    *string `xml:"WMIConnectionName,attr"`
}

// WMITaskDataOverwriteDestinationEnum ...
type WMITaskDataOverwriteDestinationEnum string

// WMITaskDataOutputTypeEnum ...
type WMITaskDataOutputTypeEnum string

// WMIEWTaskDataObjectDataType ...
type WMIEWTaskDataObjectDataType struct {
	WMIConnectionNameAttr  *string `xml:"WMIConnectionName,attr"`
	WQLQuerySourceTypeAttr *string `xml:"WQLQuerySourceType,attr"`
	WQLQuerySourceAttr     *string `xml:"WQLQuerySource,attr"`
	ActionAtEventAttr      *string `xml:"ActionAtEvent,attr"`
	AfterEventAttr         *string `xml:"AfterEvent,attr"`
	ActionAtTimeoutAttr    *string `xml:"ActionAtTimeout,attr"`
	AfterTimeoutAttr       *string `xml:"AfterTimeout,attr"`
	NumberOfEventsAttr     *int    `xml:"NumberOfEvents,attr"`
	TimeoutAttr            *int    `xml:"Timeout,attr"`
}

// WMIEWTaskDataActionAtEventEnum ...
type WMIEWTaskDataActionAtEventEnum string

// WMIEWTaskDataAfterEventEnum ...
type WMIEWTaskDataAfterEventEnum string

// WMIEWTaskDataActionAtTimeoutEnum ...
type WMIEWTaskDataActionAtTimeoutEnum string

// XMLTaskDataObjectDataType ...
type XMLTaskDataObjectDataType struct {
	OperationTypeAttr           *string `xml:"OperationType,attr"`
	SourceTypeAttr              *string `xml:"SourceType,attr"`
	SourceAttr                  *string `xml:"Source,attr"`
	SecondOperandTypeAttr       *string `xml:"SecondOperandType,attr"`
	SecondOperandAttr           *string `xml:"SecondOperand,attr"`
	SaveOperationResultAttr     *string `xml:"SaveOperationResult,attr"`
	DestinationTypeAttr         *string `xml:"DestinationType,attr"`
	DestinationAttr             *string `xml:"Destination,attr"`
	OverwriteDestinationAttr    *string `xml:"OverwriteDestination,attr"`
	FailOpOnValidationFailAttr  *string `xml:"FailOpOnValidationFail,attr"`
	FailOpOnDifferenceAttr      *string `xml:"FailOpOnDifference,attr"`
	SaveDiffGramAttr            *string `xml:"SaveDiffGram,attr"`
	DiffGramDestinationTypeAttr *string `xml:"DiffGramDestinationType,attr"`
	DiffGramDestinationAttr     *string `xml:"DiffGramDestination,attr"`
	DiffOptionsAttr             *int    `xml:"DiffOptions,attr"`
	DiffAlgorithmAttr           *string `xml:"DiffAlgorithm,attr"`
	XPathStringSourceTypeAttr   *string `xml:"XPathStringSourceType,attr"`
	XPathStringSourceAttr       *string `xml:"XPathStringSource,attr"`
	XPathOperationAttr          *string `xml:"XPathOperation,attr"`
	PutResultInOneNodeAttr      *string `xml:"PutResultInOneNode,attr"`
	ValidationTypeAttr          *string `xml:"ValidationType,attr"`
}

// XMLTaskOperationTypeEnum ...
type XMLTaskOperationTypeEnum string

// XMLTaskDiffOptionsType ...
type XMLTaskDiffOptionsType int

// XMLTaskDiffAlgorithmEnum ...
type XMLTaskDiffAlgorithmEnum string

// XMLTaskXPathOperationEnum ...
type XMLTaskXPathOperationEnum string

// XMLTaskValidationTypeEnum ...
type XMLTaskValidationTypeEnum string

// InnerObjectObjectDataType ...
type InnerObjectObjectDataType struct {
}

// PipelineObjectDataType ...
type PipelineObjectDataType struct {
	IdAttr                    *string                 `xml:"id,attr"`
	NameAttr                  *string                 `xml:"name,attr"`
	DescriptionAttr           *string                 `xml:"description,attr"`
	DefaultBufferMaxRowsAttr  *int                    `xml:"defaultBufferMaxRows,attr"`
	EngineThreadsAttr         *int                    `xml:"engineThreads,attr"`
	DefaultBufferSizeAttr     *int                    `xml:"defaultBufferSize,attr"`
	BLOBTempStoragePathAttr   *string                 `xml:"BLOBTempStoragePath,attr"`
	BufferTempStoragePathAttr *string                 `xml:"bufferTempStoragePath,attr"`
	RunInOptimizedModeAttr    *bool                   `xml:"runInOptimizedMode,attr"`
	Components                *PipelineComponentsType `xml:"components"`
	Paths                     *PipelinePathsType      `xml:"paths"`
}

// PipelineComponentsType ...
type PipelineComponentsType struct {
	Component []*PipelineComponentType `xml:"component"`
}

// PipelinePathsType ...
type PipelinePathsType struct {
	Path []*PipelinePathType `xml:"path"`
}

// PipelineComponentType ...
type PipelineComponentType struct {
	IdAttr                       *string                           `xml:"id,attr"`
	NameAttr                     *string                           `xml:"name,attr"`
	ComponentClassIDAttr         *string                           `xml:"componentClassID,attr"`
	DescriptionAttr              *string                           `xml:"description,attr"`
	LocaleIdAttr                 *int                              `xml:"localeId,attr"`
	UsesDispositionsAttr         *bool                             `xml:"usesDispositions,attr"`
	ValidateExternalMetadataAttr *string                           `xml:"validateExternalMetadata,attr"`
	VersionAttr                  *int                              `xml:"version,attr"`
	PipelineVersionAttr          *int                              `xml:"pipelineVersion,attr"`
	ContactInfoAttr              *string                           `xml:"contactInfo,attr"`
	Properties                   *PipelineComponentPropertiesType  `xml:"properties"`
	Connections                  *PipelineComponentConnectionsType `xml:"connections"`
	Inputs                       *PipelineComponentInputsType      `xml:"inputs"`
	Outputs                      *PipelineComponentOutputsType     `xml:"outputs"`
}

// PipelineComponentPropertiesType ...
type PipelineComponentPropertiesType struct {
	Property []*PipelineComponentPropertyType `xml:"property"`
}

// PipelineComponentOutputPropertiesType ...
type PipelineComponentOutputPropertiesType struct {
	Property []*PipelineComponentOutputPropertyType `xml:"property"`
}

// PipelineComponentInputPropertiesType ...
type PipelineComponentInputPropertiesType struct {
	Property []*PipelineComponentInputPropertyType `xml:"property"`
}

// PipelineComponentConnectionsType ...
type PipelineComponentConnectionsType struct {
	Connection []*PipelineComponentConnectionType `xml:"connection"`
}

// PipelineComponentInputsType ...
type PipelineComponentInputsType struct {
	Input []*PipelineComponentInputType `xml:"input"`
}

// PipelineComponentOutputsType ...
type PipelineComponentOutputsType struct {
	Output []*PipelineComponentOutputType `xml:"output"`
}

// ArrayElements ...
type ArrayElements struct {
	XMLName xml.Name `xml:"arrayElements"`
}

// AnySimpleType represents any simple type value from XML schema
type AnySimpleType struct {
	Value string `xml:",chardata"`
}

// Test ...
type Test struct {
	ArrayElements *ArrayElements `xml:"arrayElements"`
}

// PipelineComponentPropertyType ...
type PipelineComponentPropertyType struct {
	*PipelineComponentPropertyAttributeGroup
	NameAttr      *string                             `xml:"name,attr"`
	ArrayElements *PipelineComponentArrayElementsType `xml:"arrayElements"`
	Value         string                              `xml:",chardata"`
}

// PipelineComponentPropertyAttributeGroup ...
type PipelineComponentPropertyAttributeGroup struct {
	IdAttr             string `xml:"id,attr,omitempty"`
	DataTypeAttr       string `xml:"dataType,attr,omitempty"`
	NameAttr           string `xml:"name,attr,omitempty"`
	StateAttr          string `xml:"state,attr,omitempty"`
	IsArrayAttr        bool   `xml:"isArray,attr,omitempty"`
	DescriptionAttr    string `xml:"description,attr,omitempty"`
	TypeConverterAttr  string `xml:"typeConverter,attr,omitempty"`
	UITypeEditorAttr   string `xml:"UITypeEditor,attr,omitempty"`
	ContainsIDAttr     bool   `xml:"containsID,attr,omitempty"`
	ExpressionTypeAttr string `xml:"expressionType,attr,omitempty"`
}

// PipelineComponentOutputPropertyType ...
type PipelineComponentOutputPropertyType struct {
	*PipelineComponentPropertyAttributeGroup
	NameAttr      *string                             `xml:"name,attr"`
	ArrayElements *PipelineComponentArrayElementsType `xml:"arrayElements"`
}

// PipelineComponentInputPropertyType ...
type PipelineComponentInputPropertyType struct {
	*PipelineComponentPropertyAttributeGroup
	NameAttr      *string                             `xml:"name,attr"`
	ArrayElements *PipelineComponentArrayElementsType `xml:"arrayElements"`
}

// PipelineComponentArrayElementsType ...
type PipelineComponentArrayElementsType struct {
	ArrayElementCountAttr *int                                 `xml:"arrayElementCount,attr"`
	ArrayElement          []*PipelineComponentArrayElementType `xml:"arrayElement"`
}

// PipelineComponentArrayElementType ...
type PipelineComponentArrayElementType struct {
	DataTypeAttr *string `xml:"dataType,attr"`
	*AnySimpleType
}

// PipelineComponentComponentClassIDEnum ...
type PipelineComponentComponentClassIDEnum string

// PipelineComponentPropertyNameEnum ...
type PipelineComponentPropertyNameEnum string

// PipelineComponentOutputPropertyNameEnum ...
type PipelineComponentOutputPropertyNameEnum string

// PipelineComponentInputPropertyNameEnum ...
type PipelineComponentInputPropertyNameEnum string

// PipelineComponentOutputColumnPropertyNameEnum ...
type PipelineComponentOutputColumnPropertyNameEnum string

// PipelineComponentInputColumnPropertyNameEnum ...
type PipelineComponentInputColumnPropertyNameEnum string

// PipelineComponentDataTypeEnum ...
type PipelineComponentDataTypeEnum string

// PipelineComponentStateEnum ...
type PipelineComponentStateEnum string

// PipelineComponentExpressionTypeEnum ...
type PipelineComponentExpressionTypeEnum string

// PipelineComponentConnectionType ...
type PipelineComponentConnectionType struct {
	IdAttr                  *string `xml:"id,attr"`
	NameAttr                *string `xml:"name,attr"`
	DescriptionAttr         *string `xml:"description,attr"`
	ConnectionManagerIDAttr *string `xml:"connectionManagerID,attr"`
}

// PipelineComponentInputType ...
type PipelineComponentInputType struct {
	*PipelineComponentInputOutputElementAttributeGroup
	Properties              *PipelineComponentInputPropertiesType `xml:"properties"`
	InputColumns            *PipelineComponentInputColumnsType    `xml:"inputColumns"`
	ExternalMetadataColumns *PipelineComponentMetadataColumnsType `xml:"externalMetadataColumns"`
}

// PipelineComponentInputColumnsType ...
type PipelineComponentInputColumnsType struct {
	InputColumn []*PipelineComponentInputColumnType `xml:"inputColumn"`
}

// PipelineComponentInputColumnType ...
type PipelineComponentInputColumnType struct {
	*PipelineComponentAllColumnBaseAttributeGroup
	*PipelineComponentIOColumnBaseAttributeGroup
	UsageTypeAttr *string                                       `xml:"usageType,attr"`
	Properties    []*PipelineComponentInputColumnPropertiesType `xml:"properties"`
}

// PipelineComponentInputColumnPropertiesType ...
type PipelineComponentInputColumnPropertiesType struct {
	Property []*PipelineComponentInputColumnPropertyType `xml:"property"`
}

// PipelineComponentInputColumnPropertyType ...
type PipelineComponentInputColumnPropertyType struct {
	*PipelineComponentPropertyAttributeGroup
	NameAttr *string `xml:"name,attr"`
	*AnySimpleType
}

// PipelineComponentOutputColumnPropertiesType ...
type PipelineComponentOutputColumnPropertiesType struct {
	Property []*PipelineComponentOutputColumnPropertyType `xml:"property"`
}

// PipelineComponentOutputColumnPropertyType ...
type PipelineComponentOutputColumnPropertyType struct {
	*PipelineComponentPropertyAttributeGroup
	NameAttr *string `xml:"name,attr"`
	*AnySimpleType
}

// PipelineComponentUsageTypeEnum ...
type PipelineComponentUsageTypeEnum string

// PipelineComponentOutputType ...
type PipelineComponentOutputType struct {
	*PipelineComponentInputOutputElementAttributeGroup
	ExclusionGroupAttr             *int                                   `xml:"exclusionGroup,attr"`
	SynchronousInputIdAttr         *string                                `xml:"synchronousInputId,attr"`
	DeleteOutputOnPathDetachedAttr *bool                                  `xml:"deleteOutputOnPathDetached,attr"`
	IsErrorOutAttr                 *bool                                  `xml:"isErrorOut,attr"`
	IsSortedAttr                   *bool                                  `xml:"isSorted,attr"`
	Properties                     *PipelineComponentOutputPropertiesType `xml:"properties"`
	OutputColumns                  *PipelineComponentOutputColumnsType    `xml:"outputColumns"`
	ExternalMetadataColumns        *PipelineComponentMetadataColumnsType  `xml:"externalMetadataColumns"`
}

// PipelineComponentMetadataColumnsType ...
type PipelineComponentMetadataColumnsType struct {
	IsUsedAttr             *string                                `xml:"isUsed,attr"`
	ExternalMetadataColumn []*PipelineComponentMetadataColumnType `xml:"externalMetadataColumn"`
}

// PipelineComponentMetadataColumnType ...
type PipelineComponentMetadataColumnType struct {
	*PipelineComponentAllColumnBaseAttributeGroup
	*PipelineComponentColumnExtendedAttributeGroup
	Properties *PipelineComponentMetadataColumnPropertiesType `xml:"properties"`
}

// PipelineComponentMetadataColumnPropertiesType ...
type PipelineComponentMetadataColumnPropertiesType struct {
	Property []*PipelineComponentMetadataColumnPropertyType `xml:"property"`
}

// PipelineComponentMetadataColumnPropertyType ...
type PipelineComponentMetadataColumnPropertyType struct {
	*PipelineComponentPropertyAttributeGroup
	NameAttr *string `xml:"name,attr"`
	*AnySimpleType
}

// PipelineComponentMetadataColumnPropertyNameEnum ...
type PipelineComponentMetadataColumnPropertyNameEnum string

// PipelineComponentInputOutputElementAttributeGroup ...
type PipelineComponentInputOutputElementAttributeGroup struct {
	IdAttr                         string `xml:"id,attr,omitempty"`
	NameAttr                       string `xml:"name,attr,omitempty"`
	DescriptionAttr                string `xml:"description,attr,omitempty"`
	HasSideEffectsAttr             bool   `xml:"hasSideEffects,attr,omitempty"`
	DanglingAttr                   bool   `xml:"dangling,attr,omitempty"`
	ErrorOrTruncationOperationAttr string `xml:"errorOrTruncationOperation,attr,omitempty"`
	ErrorRowDispositionAttr        string `xml:"errorRowDisposition,attr,omitempty"`
	TruncationRowDispositionAttr   string `xml:"truncationRowDisposition,attr,omitempty"`
}

// PipelineComponentAllColumnBaseAttributeGroup ...
type PipelineComponentAllColumnBaseAttributeGroup struct {
	IdAttr             string `xml:"id,attr,omitempty"`
	NameAttr           string `xml:"name,attr,omitempty"`
	DescriptionAttr    string `xml:"description,attr,omitempty"`
	MappedColumnIdAttr string `xml:"mappedColumnId,attr,omitempty"`
}

// PipelineComponentIOColumnBaseAttributeGroup ...
type PipelineComponentIOColumnBaseAttributeGroup struct {
	ErrorOrTruncationOperationAttr string `xml:"errorOrTruncationOperation,attr,omitempty"`
	ErrorRowDispositionAttr        string `xml:"errorRowDisposition,attr,omitempty"`
	TruncationRowDispositionAttr   string `xml:"truncationRowDisposition,attr,omitempty"`
	ExternalMetadataColumnIdAttr   string `xml:"externalMetadataColumnId,attr,omitempty"`
	LineageIdAttr                  string `xml:"lineageId,attr,omitempty"`
}

// PipelineComponentColumnExtendedAttributeGroup ...
type PipelineComponentColumnExtendedAttributeGroup struct {
	PrecisionAttr int    `xml:"precision,attr,omitempty"`
	ScaleAttr     int    `xml:"scale,attr,omitempty"`
	LengthAttr    int    `xml:"length,attr,omitempty"`
	DataTypeAttr  string `xml:"dataType,attr,omitempty"`
	CodePageAttr  int    `xml:"codePage,attr,omitempty"`
}

// PipelineComponentOutputColumnsType ...
type PipelineComponentOutputColumnsType struct {
	OutputColumn []*PipelineComponentOutputColumnType `xml:"outputColumn"`
}

// PipelineComponentOutputColumnType ...
type PipelineComponentOutputColumnType struct {
	*PipelineComponentAllColumnBaseAttributeGroup
	*PipelineComponentIOColumnBaseAttributeGroup
	*PipelineComponentColumnExtendedAttributeGroup
	SortKeyPositionAttr *int                                           `xml:"sortKeyPosition,attr"`
	ComparisonFlagsAttr *int                                           `xml:"comparisonFlags,attr"`
	SpecialFlagsAttr    *int                                           `xml:"specialFlags,attr"`
	Properties          []*PipelineComponentOutputColumnPropertiesType `xml:"properties"`
}

// PipelineComponentColumnDataTypeEnum ...
type PipelineComponentColumnDataTypeEnum string

// PipelineComponentRowDispositionEnum ...
type PipelineComponentRowDispositionEnum string

// PipelinePathType ...
type PipelinePathType struct {
	IdAttr          *string `xml:"id,attr"`
	NameAttr        *string `xml:"name,attr"`
	DescriptionAttr *string `xml:"description,attr"`
	StartIdAttr     *string `xml:"startId,attr"`
	EndIdAttr       *string `xml:"endId,attr"`
}

// LogProviderObjectDataType ...
type LogProviderObjectDataType struct {
	InnerObject *InnerObjectObjectDataType `xml:"InnerObject"`
}

// ForEachEnumeratorObjectDataType ...
type ForEachEnumeratorObjectDataType struct {
	FEIEItems                       *FEIEItemsType                       `xml:"FEIEItems"`
	ForEachFileEnumeratorProperties *ForEachFileEnumeratorPropertiesType `xml:"ForEachFileEnumeratorProperties"`
	FEEADO                          *FEEADOType                          `xml:"FEEADO"`
	FEESchemaRowset                 *FEESchemaRowsetType                 `xml:"FEESchemaRowset"`
	FEEFVE                          *FEEFVEType                          `xml:"FEEFVE"`
	FEENODELIST                     *FEENODELISTType                     `xml:"FEENODELIST"`
	FEESMO                          *FEESMOType                          `xml:"FEESMO"`
}

// FEIEItemsType ...
type FEIEItemsType struct {
	FEIEItem []*FEIEItemType `xml:"FEIEItem"`
}

// FEIEItemType ...
type FEIEItemType struct {
	FEIEItemValue []*FEIEItemValueType `xml:"FEIEItemValue"`
}

// FEIEItemValueType ...
type FEIEItemValueType struct {
	TypeAttr  int    `xml:"Type,attr"`
	ValueAttr string `xml:"Value,attr"`
}

// FEFEProperty ...
type FEFEProperty struct {
	FolderAttr                *interface{} `xml:"Folder,attr"`
	FileSpecAttr              *interface{} `xml:"FileSpec,attr"`
	FileNameRetrievalTypeAttr *int         `xml:"FileNameRetrievalType,attr"`
	RecurseAttr               *int         `xml:"Recurse,attr"`
}

// ForEachFileEnumeratorPropertiesType ...
type ForEachFileEnumeratorPropertiesType struct {
	FEFEProperty []*FEFEProperty `xml:"FEFEProperty"`
}

// FEEADOType ...
type FEEADOType struct {
	EnumTypeAttr string `xml:"EnumType,attr"`
	VarNameAttr  string `xml:"VarName,attr"`
}

// FEEADOEnumType ...
type FEEADOEnumType string

// FEESchemaRowsetType ...
type FEESchemaRowsetType struct {
	ConnectionAttr string                    `xml:"Connection,attr"`
	SchemaAttr     string                    `xml:"Schema,attr"`
	Restriction    []*RestrictionElementType `xml:"Restriction"`
}

// RestrictionElementType ...
type RestrictionElementType struct {
	IndexAttr int    `xml:"Index,attr"`
	ValueAttr string `xml:"Value,attr"`
}

// FEEFVEType ...
type FEEFVEType struct {
	VariableNameAttr string `xml:"VariableName,attr"`
}

// FEENODELISTType ...
type FEENODELISTType struct {
	EnumerationTypeAttr      string `xml:"EnumerationType,attr"`
	OuterXPathSourceTypeAttr string `xml:"OuterXPathSourceType,attr"`
	OuterXPathStringAttr     string `xml:"OuterXPathString,attr"`
	InnerElementTypeAttr     string `xml:"InnerElementType,attr"`
	InnerXPathSourceTypeAttr string `xml:"InnerXPathSourceType,attr"`
	InnerXPathStringAttr     string `xml:"InnerXPathString,attr"`
	SourceTypeAttr           string `xml:"SourceType,attr"`
	SourceDocumentAttr       string `xml:"SourceDocument,attr"`
}

// NodelistInnerElementEnumerationTypeEnum ...
type NodelistInnerElementEnumerationTypeEnum string

// NodelistEnumerationTypeEnum ...
type NodelistEnumerationTypeEnum string

// FEESMOType ...
type FEESMOType struct {
	EnumURNAttr string `xml:"EnumURN,attr"`
}

// ConnectionManagerObjectDataType ...
type ConnectionManagerObjectDataType struct {
	ConnectionManager          *ConnectionManagerObjectDataConnectionManagerType          `xml:"ConnectionManager"`
	MsmqConnectionManager      *ConnectionManagerObjectDataMsmqConnectionManagerType      `xml:"MsmqConnectionManager"`
	SMOServerConnectionManager *ConnectionManagerObjectDataSMOServerConnectionManagerType `xml:"SMOServerConnectionManager"`
	SmtpConnectionManager      *ConnectionManagerObjectDataSmtpConnectionManagerType      `xml:"SmtpConnectionManager"`
	WmiConnectionManager       *ConnectionManagerObjectDataWmiConnectionManagerType       `xml:"WmiConnectionManager"`
}

// ConnectionManagerObjectDataConnectionManagerType ...
type ConnectionManagerObjectDataConnectionManagerType struct {
	ConnectRetryCountAttr    *string               `xml:"ConnectRetryCount,attr"`
	ConnectRetryIntervalAttr *string               `xml:"ConnectRetryInterval,attr"`
	ConnectionStringAttr     *string               `xml:"ConnectionString,attr"`
	Property                 []*Property           `xml:"Property"`
	FlatFileColumn           []*FlatFileColumnType `xml:"FlatFileColumn"`
	CacheColumn              []*CacheColumnType    `xml:"CacheColumn"`
	FtpConnection            *FtpConnectionType    `xml:"FtpConnection"`
	HttpConnection           *HttpConnectionType   `xml:"HttpConnection"`
}

// FlatFileColumnType ...
type FlatFileColumnType struct {
	Property []*Property `xml:"Property"`
}

// CacheColumnType ...
type CacheColumnType struct {
	Property []*Property `xml:"Property"`
}

// FtpConnectionType ...
type FtpConnectionType struct {
	Property []*Property `xml:"Property"`
}

// HttpConnectionType ...
type HttpConnectionType struct {
	Property []*Property `xml:"Property"`
}

// ConnectionManagerObjectDataMsmqConnectionManagerType ...
type ConnectionManagerObjectDataMsmqConnectionManagerType struct {
	ConnectionStringAttr *string `xml:"ConnectionString,attr"`
}

// ConnectionManagerObjectDataSMOServerConnectionManagerType ...
type ConnectionManagerObjectDataSMOServerConnectionManagerType struct {
	ConnectionStringAttr string               `xml:"ConnectionString,attr"`
	PassWord             *PasswordElementType `xml:"PassWord"`
}

// PasswordElementType ...
type PasswordElementType struct {
	SensitiveAttr *int   `xml:"Sensitive,attr"`
	EncryptedAttr *int   `xml:"Encrypted,attr"`
	Value         string `xml:",chardata"`
}

// ConnectionManagerObjectDataSmtpConnectionManagerType ...
type ConnectionManagerObjectDataSmtpConnectionManagerType struct {
	ConnectionStringAttr *string `xml:"ConnectionString,attr"`
}

// ConnectionManagerObjectDataWmiConnectionManagerType ...
type ConnectionManagerObjectDataWmiConnectionManagerType struct {
	ConnectionStringAttr *string              `xml:"ConnectionString,attr"`
	PassWord             *PasswordElementType `xml:"PassWord"`
}

// PropertyElementBaseType ...
type PropertyElementBaseType struct {
	DataTypeAttr *int `xml:"DataType,attr"`
	*AnySimpleType
}

// PropertyExpressionElementType ...
type PropertyExpressionElementType struct {
	NameAttr string `xml:"Name,attr"`
	*AnySimpleType
}

// BasePropertyNameEnum ...
type BasePropertyNameEnum string

// DtsDataTypeEnum ...
type DtsDataTypeEnum int

// AllExecutablePropertyNameEnum ...
type AllExecutablePropertyNameEnum struct {
	BaseExecutablePropertyNameEnum *BaseExecutablePropertyNameEnum
}

// BaseExecutablePropertyNameEnum ...
type BaseExecutablePropertyNameEnum struct {
	BasePropertyNameEnum string
}

// ExecutableTypePackagePropertyNameEnum ...
type ExecutableTypePackagePropertyNameEnum struct {
	AllExecutablePropertyNameEnum *AllExecutablePropertyNameEnum
}

// AnyNonPackageExecutablePropertyNameEnum ...
type AnyNonPackageExecutablePropertyNameEnum struct {
	AllExecutablePropertyNameEnum *AllExecutablePropertyNameEnum
}

// LogProviderPropertyNameEnum ...
type LogProviderPropertyNameEnum struct {
	BasePropertyNameEnum string
}

// PackageVariablePropertyNameEnum ...
type PackageVariablePropertyNameEnum struct {
	BasePropertyNameEnum string
}

// ConfigurationPropertyNameEnum ...
type ConfigurationPropertyNameEnum struct {
	BasePropertyNameEnum string
}

// PrecedenceConstraintPropertyNameEnum ...
type PrecedenceConstraintPropertyNameEnum struct {
	BasePropertyNameEnum string
}

// LoggingOptionsPropertyNameEnum ...
type LoggingOptionsPropertyNameEnum string

// ColumnEventFilterPropertyNameEnum ...
type ColumnEventFilterPropertyNameEnum string

// ForEachVariableMappingPropertyNameEnum ...
type ForEachVariableMappingPropertyNameEnum struct {
	BasePropertyNameEnum string
}

// VariablePropertyNameEnum ...
type VariablePropertyNameEnum struct {
	BasePropertyNameEnum string
}

// ConnectionManagerPropertyNameEnum ...
type ConnectionManagerPropertyNameEnum struct {
	BasePropertyNameEnum string
}

// ConnectionManagerObjectDataPropertyNameEnum ...
type ConnectionManagerObjectDataPropertyNameEnum string

// FlatFileColumnPropertyNameEnum ...
type FlatFileColumnPropertyNameEnum struct {
	BasePropertyNameEnum string
}

// CacheColumnPropertyNameEnum ...
type CacheColumnPropertyNameEnum struct {
	BasePropertyNameEnum string
}

// FtpConnectionPropertyNameEnum ...
type FtpConnectionPropertyNameEnum string

// HttpConnectionPropertyNameEnum ...
type HttpConnectionPropertyNameEnum string

// EventHandlerPropertyNameEnum ...
type EventHandlerPropertyNameEnum struct {
	BaseExecutablePropertyNameEnum *BaseExecutablePropertyNameEnum
}

// FileSystemTaskOperationTypeEnum ...
type FileSystemTaskOperationTypeEnum string

// FileSystemTaskFileAttributesEnum ...
type FileSystemTaskFileAttributesEnum string

// SourceTypeEnum ...
type SourceTypeEnum string

// Uuid ...
type Uuid string
