// Code generated by xgen. DO NOT EDIT.

package schema

// ActiveXScriptTaskData ...
type ActiveXScriptTaskData *ActiveXScriptTaskDataType

// ActiveXScriptTaskDataType ...
type ActiveXScriptTaskDataType struct {
	ScriptingLanguageAttr *string `xml:"ScriptingLanguage,attr"`
	ScriptTextAttr        *string `xml:"ScriptText,attr"`
	EntryMethodAttr       *string `xml:"EntryMethod,attr"`
}

// ScriptingLanguageEnum ...
type ScriptingLanguageEnum string
