// Code generated by xgen. DO NOT EDIT.

package schema

// BulkInsertTaskData ...
type BulkInsertTaskData *BulkInsertTaskDataType

// BulkInsertTaskDataType ...
type BulkInsertTaskDataType struct {
	BatchSizeAttr                 *CodePageType `xml:"BatchSize,attr,omitempty"`
	CheckConstraintsAttr          *string       `xml:"CheckConstraints,attr"`
	CodePageAttr                  *string       `xml:"CodePage,attr"`
	SourceConnectionNameAttr      *string       `xml:"SourceConnectionName,attr"`
	DestinationConnectionNameAttr *string       `xml:"DestinationConnectionName,attr"`
	DataFileTypeAttr              *string       `xml:"DataFileType,attr"`
	DestinationTableNameAttr      *string       `xml:"DestinationTableName,attr"`
	FirstRowAttr                  *int          `xml:"FirstRow,attr"`
	LastRowAttr                   *int          `xml:"LastRow,attr"`
	UseFormatFileAttr             *string       `xml:"UseFormatFile,attr"`
	FormatFileAttr                *string       `xml:"FormatFile,attr"`
	SortedDataAttr                *string       `xml:"SortedData,attr"`
	TableLockAttr                 *string       `xml:"TableLock,attr"`
	KeepIdentityAttr              *string       `xml:"KeepIdentity,attr"`
	KeepNullsAttr                 *string       `xml:"KeepNulls,attr"`
	FieldTerminatorAttr           *string       `xml:"FieldTerminator,attr"`
	RowTerminatorAttr             *string       `xml:"RowTerminator,attr"`
	FireTriggersAttr              *string       `xml:"FireTriggers,attr"`
	MaximumErrorsAttr             *int          `xml:"MaximumErrors,attr"`
}

// DataFileTypeEnum ...
type DataFileTypeEnum string

// CodePageType ...
type CodePageType struct {
	Int int
}

// BulkInsertTaskTerminatorEnum ...
type BulkInsertTaskTerminatorEnum string
