// Code generated by xgen. DO NOT EDIT.

package schema

// Exec80PackageTaskData ...
type Exec80PackageTaskData *Exec80PackageTaskType

// Exec80PackageTaskType ...
type Exec80PackageTaskType struct {
	LocationAttr              *string `xml:"Location,attr"`
	PackageNameAttr           *string `xml:"PackageName,attr"`
	PackageIDAttr             *string `xml:"PackageID,attr"`
	PackageVersionGUIDAttr    *string `xml:"PackageVersionGUID,attr"`
	SQLServerAttr             *string `xml:"SQLServer,attr"`
	SQLUsernameAttr           *string `xml:"SQLUsername,attr"`
	WindowsAuthenticationAttr *string `xml:"WindowsAuthentication,attr"`
	FilenameAttr              *string `xml:"Filename,attr"`
	InnerGlobalVariablesAttr  *string `xml:"InnerGlobalVariables,attr"`
	OuterGlobalVariablesAttr  *string `xml:"OuterGlobalVariables,attr"`
	DTS2000Package            *string `xml:"DTS2000Package"`
}

// Exec80PackageTaskLocationEnum ...
type Exec80PackageTaskLocationEnum string
