// Code generated by xgen. DO NOT EDIT.

package schema

// MessageQueueTaskData ...
type MessageQueueTaskData *MessageQueueTaskType

// MessageQueueTaskType ...
type MessageQueueTaskType struct {
	CurrentPackageIDAttr            *string `xml:"CurrentPackageID,attr"`
	TaskDescriptionAttr             *string `xml:"TaskDescription,attr"`
	DataFileOverWritableAttr        *string `xml:"DataFileOverWritable,attr"`
	DTSMessageLineageIDAttr         *string `xml:"DTSMessageLineageID,attr"`
	DTSMessagePackageIDAttr         *string `xml:"DTSMessagePackageID,attr"`
	DTSMessageVersionIDAttr         *string `xml:"DTSMessageVersionID,attr"`
	ErrorIfMessageTimeOutAttr       *string `xml:"ErrorIfMessageTimeOut,attr"`
	QueuePathAttr                   *string `xml:"QueuePath,attr"`
	ReceiveMessageTimeOutAttr       *int    `xml:"ReceiveMessageTimeOut,attr"`
	ReceiveMessageTypeAttr          *string `xml:"ReceiveMessageType,attr"`
	RemoveFromQueueAttr             *string `xml:"RemoveFromQueue,attr"`
	SaveDataFileNameAttr            *string `xml:"SaveDataFileName,attr"`
	StringCompareTypeAttr           *string `xml:"StringCompareType,attr"`
	StringCompareValueAttr          *string `xml:"StringCompareValue,attr"`
	StringMessageToVariableNameAttr *string `xml:"StringMessageToVariableName,attr"`
	ReceiveVariableMessageAttr      *string `xml:"ReceiveVariableMessage,attr"`
	TaskTypeAttr                    *string `xml:"TaskType,attr"`
	UseEncryptionAttr               *string `xml:"UseEncryption,attr"`
	EncryptionAlgorithmAttr         *string `xml:"EncryptionAlgorithm,attr"`
	Use2000FormatAttr               *string `xml:"Use2000Format,attr"`
	DataFileNameAttr                *string `xml:"DataFileName,attr"`
	StringMessageAttr               *string `xml:"StringMessage,attr"`
	VariableMessageAttr             *string `xml:"VariableMessage,attr"`
	MessageTypeAttr                 *string `xml:"MessageType,attr"`
}

// MSMQStringCompareTypeEnum ...
type MSMQStringCompareTypeEnum string

// MSMQTaskTypeEnum ...
type MSMQTaskTypeEnum string

// MSMQMessageTypeEnum ...
type MSMQMessageTypeEnum string

// MSMQEncryptionAlgorithmEnum ...
type MSMQEncryptionAlgorithmEnum string
