// Code generated by xgen. DO NOT EDIT.

package schema

// SendMailTaskData ...
type SendMailTaskData *SendMailTaskType

// SendMailTaskType ...
type SendMailTaskType struct {
	SMTPServerAttr        *string                 `xml:"SMTPServer,attr"`
	FromAttr              *string                 `xml:"From,attr"`
	ToAttr                *string                 `xml:"To,attr"`
	CCAttr                *string                 `xml:"CC,attr"`
	BCCAttr               *string                 `xml:"BCC,attr"`
	SubjectAttr           *string                 `xml:"Subject,attr"`
	PriorityAttr          *string                 `xml:"Priority,attr"`
	MessageSourceTypeAttr *string                 `xml:"MessageSourceType,attr"`
	MessageSourceAttr     *string                 `xml:"MessageSource,attr"`
	Attachments           *AttachmentsElementType `xml:"Attachments"`
}

// SendMailPriorityEnum ...
type SendMailPriorityEnum string

// AttachmentsElementType ...
type AttachmentsElementType struct {
	FileNameAttr *string `xml:"FileName,attr"`
}
