// Code generated by xgen. DO NOT EDIT.

package schema

// SqlTaskData ...
type SqlTaskData *SqlTaskDataType

// SqlTaskDataType ...
type SqlTaskDataType struct {
	SQLTaskSqlTaskBaseAttributeGroup                *SqlTaskBaseAttributeGroup
	SQLTaskMaintenanceTaskBaseAttributeGroup        *MaintenanceTaskBaseAttributeGroup
	SQLTaskBackupTaskAttributeGroup                 *BackupTaskAttributeGroup
	SQLTaskCheckIntegrityTaskAttributeGroup         *CheckIntegrityTaskAttributeGroup
	SQLTaskAgentJobTaskAttributeGroup               *AgentJobTaskAttributeGroup
	SQLTaskHistoryCleanupTaskAttributeGroup         *HistoryCleanupTaskAttributeGroup
	SQLTaskMaintenanceFileCleanupTaskAttributeGroup *MaintenanceFileCleanupTaskAttributeGroup
	SQLTaskNotifyOperatorTaskAttributeGroup         *NotifyOperatorTaskAttributeGroup
	SQLTaskRebuildIndexTaskAttributeGroup           *RebuildIndexTaskAttributeGroup
	SQLTaskReorganizeIndexTaskAttributeGroup        *ReorganizeIndexTaskAttributeGroup
	SQLTaskShrinkDBTaskAttributeGroup               *ShrinkDBTaskAttributeGroup
	SQLTaskUpdateStatisticsTaskAttributeGroup       *UpdateStatisticsTaskAttributeGroup
	RemoveOlderThanAttr                             *int                           `xml:"RemoveOlderThan,attr"`
	TimeUnitsTypeAttr                               *int                           `xml:"TimeUnitsType,attr"`
	DatabaseSelectionTypeAttr                       *int                           `xml:"DatabaseSelectionType,attr"`
	SelectedDatabases                               []*SelectedDatabasesType       `xml:"SelectedDatabases"`
	OperatorNotifyList                              []*OperatorNotifyListType      `xml:"OperatorNotifyList"`
	ParameterBinding                                []*SqlTaskParameterBindingType `xml:"ParameterBinding"`
	ResultBinding                                   *SqlTaskResultBindingType      `xml:"ResultBinding"`
	BackupDestinationList                           []*BackupDestinationListType   `xml:"BackupDestinationList"`
}

// SqlResultTypeEnum ...
type SqlResultTypeEnum string

// SelectedDatabasesType ...
type SelectedDatabasesType struct {
	DatabaseNameAttr *string `xml:"DatabaseName,attr"`
}

// OperatorNotifyListType ...
type OperatorNotifyListType struct {
	OperatorNotifyAttr *string `xml:"OperatorNotify,attr"`
}

// SqlTaskParameterBindingType ...
type SqlTaskParameterBindingType struct {
	ParameterNameAttr      *string `xml:"ParameterName,attr"`
	DtsVariableNameAttr    *string `xml:"DtsVariableName,attr"`
	ParameterDirectionAttr *string `xml:"ParameterDirection,attr"`
	DataTypeAttr           *int    `xml:"DataType,attr"`
	ParameterSizeAttr      *int    `xml:"ParameterSize,attr"`
}

// ParameterDirectionEnum ...
type ParameterDirectionEnum string

// SqlTaskResultBindingType ...
type SqlTaskResultBindingType struct {
	ResultNameAttr      *string `xml:"ResultName,attr"`
	DtsVariableNameAttr *string `xml:"DtsVariableName,attr"`
}

// BackupDestinationListType ...
type BackupDestinationListType struct {
	BackupDestinationLocationAttr *string `xml:"BackupDestinationLocation,attr"`
}

// SqlTaskBaseAttributeGroup ...
type SqlTaskBaseAttributeGroup struct {
	ConnectionAttr         string `xml:"Connection,attr,omitempty"`
	TimeOutAttr            int    `xml:"TimeOut,attr,omitempty"`
	IsStoredProcAttr       string `xml:"IsStoredProc,attr,omitempty"`
	BypassPrepareAttr      string `xml:"BypassPrepare,attr,omitempty"`
	SqlStmtSourceTypeAttr  string `xml:"SqlStmtSourceType,attr,omitempty"`
	SqlStatementSourceAttr string `xml:"SqlStatementSource,attr,omitempty"`
	CodePageAttr           int    `xml:"CodePage,attr,omitempty"`
	ResultTypeAttr         string `xml:"ResultType,attr,omitempty"`
}

// MaintenanceTaskBaseAttributeGroup ...
type MaintenanceTaskBaseAttributeGroup struct {
	ServerVersionAttr                   int    `xml:"ServerVersion,attr,omitempty"`
	ExtendedLoggingAttr                 string `xml:"ExtendedLogging,attr,omitempty"`
	LocalConnectionForLoggingAttr       string `xml:"LocalConnectionForLogging,attr,omitempty"`
	TaskNameAttr                        string `xml:"TaskName,attr,omitempty"`
	IgnoreDatabasesInNotOnlineStateAttr string `xml:"IgnoreDatabasesInNotOnlineState,attr,omitempty"`
}

// BackupTaskAttributeGroup ...
type BackupTaskAttributeGroup struct {
	BackupActionAttr                    int    `xml:"BackupAction,attr,omitempty"`
	BackupIsIncrementalAttr             string `xml:"BackupIsIncremental,attr,omitempty"`
	BackupFileGroupsFilesAttr           string `xml:"BackupFileGroupsFiles,attr,omitempty"`
	BackupDeviceTypeAttr                int    `xml:"BackupDeviceType,attr,omitempty"`
	BackupPhisycalDestinationTypeAttr   int    `xml:"BackupPhisycalDestinationType,attr,omitempty"`
	BackupDestinationTypeAttr           int    `xml:"BackupDestinationType,attr,omitempty"`
	BackupDestinationAutoFolderPathAttr string `xml:"BackupDestinationAutoFolderPath,attr,omitempty"`
	BackupActionForExistingBackupsAttr  int    `xml:"BackupActionForExistingBackups,attr,omitempty"`
	BackupCreateSubFolderAttr           string `xml:"BackupCreateSubFolder,attr,omitempty"`
	BackupFileExtensionAttr             string `xml:"BackupFileExtension,attr,omitempty"`
	BackupVerifyIntegrityAttr           string `xml:"BackupVerifyIntegrity,attr,omitempty"`
	ExpireDateAttr                      string `xml:"ExpireDate,attr,omitempty"`
	RetainDaysAttr                      int    `xml:"RetainDays,attr,omitempty"`
	InDaysAttr                          string `xml:"InDays,attr,omitempty"`
	UseExpirationAttr                   string `xml:"UseExpiration,attr,omitempty"`
	BackupCompressionActionAttr         int    `xml:"BackupCompressionAction,attr,omitempty"`
	BackupTailLogAttr                   string `xml:"BackupTailLog,attr,omitempty"`
}

// BackupActionEnum ...
type BackupActionEnum int

// BackupDeviceTypeEnum ...
type BackupDeviceTypeEnum int

// BackupPhisycalDestinationTypeEnum ...
type BackupPhisycalDestinationTypeEnum int

 

// BackupActionForExistingBackupsEnum ...
type BackupActionForExistingBackupsEnum int

// BackupCompressionActionEnum ...
type BackupCompressionActionEnum int

// CheckIntegrityTaskAttributeGroup ...
type CheckIntegrityTaskAttributeGroup struct {
	IncludeIndexesAttr string `xml:"IncludeIndexes,attr,omitempty"`
}

// SqlTaskDatabaseSelectionTypeEnum ...
type SqlTaskDatabaseSelectionTypeEnum int

// AgentJobTaskAttributeGroup ...
type AgentJobTaskAttributeGroup struct {
	AgentJobIDAttr string `xml:"AgentJobID,attr,omitempty"`
}

// HistoryCleanupTaskAttributeGroup ...
type HistoryCleanupTaskAttributeGroup struct {
	RemoveBackupRestoreHistoryAttr string `xml:"RemoveBackupRestoreHistory,attr,omitempty"`
	RemoveAgentHistoryAttr         string `xml:"RemoveAgentHistory,attr,omitempty"`
	RemoveDbMaintHistoryAttr       string `xml:"RemoveDbMaintHistory,attr,omitempty"`
}

// SqlTaskTimeUnitsTypeEnum ...
type SqlTaskTimeUnitsTypeEnum int

// MaintenanceFileCleanupTaskAttributeGroup ...
type MaintenanceFileCleanupTaskAttributeGroup struct {
	FileTypeSelectedAttr   string `xml:"FileTypeSelected,attr,omitempty"`
	FilePathAttr           string `xml:"FilePath,attr,omitempty"`
	FolderPathAttr         string `xml:"FolderPath,attr,omitempty"`
	CleanSubFoldersAttr    string `xml:"CleanSubFolders,attr,omitempty"`
	FileExtensionAttr      string `xml:"FileExtension,attr,omitempty"`
	AgeBasedAttr           string `xml:"AgeBased,attr,omitempty"`
	DeleteSpecificFileAttr string `xml:"DeleteSpecificFile,attr,omitempty"`
}

// SqlTaskFileTypeSelectedEnum ...
type SqlTaskFileTypeSelectedEnum int

// NotifyOperatorTaskAttributeGroup ...
type NotifyOperatorTaskAttributeGroup struct {
	MessageAttr string `xml:"Message,attr,omitempty"`
	ProfileAttr string `xml:"Profile,attr,omitempty"`
	SubjectAttr string `xml:"Subject,attr,omitempty"`
}

// RebuildIndexTaskAttributeGroup ...
type RebuildIndexTaskAttributeGroup struct {
	UseOriginalAmountAttr string `xml:"UseOriginalAmount,attr,omitempty"`
	PercentageAttr        int    `xml:"Percentage,attr,omitempty"`
	SortAttr              string `xml:"Sort,attr,omitempty"`
	KeepOnlineAttr        string `xml:"KeepOnline,attr,omitempty"`
}

// ReorganizeIndexTaskAttributeGroup ...
type ReorganizeIndexTaskAttributeGroup struct {
	CompactLargeObjectsAttr string `xml:"CompactLargeObjects,attr,omitempty"`
}

// ShrinkDBTaskAttributeGroup ...
type ShrinkDBTaskAttributeGroup struct {
	DatabaseSizeLimitAttr       int    `xml:"DatabaseSizeLimit,attr,omitempty"`
	DatabasePercentLimitAttr    int    `xml:"DatabasePercentLimit,attr,omitempty"`
	DatabaseReturnFreeSpaceAttr string `xml:"DatabaseReturnFreeSpace,attr,omitempty"`
}

// UpdateStatisticsTaskAttributeGroup ...
type UpdateStatisticsTaskAttributeGroup struct {
	UpdateStatisticsTypeAttr int `xml:"UpdateStatisticsType,attr,omitempty"`
	UpdateScanTypeAttr       int `xml:"UpdateScanType,attr,omitempty"`
	UpdateSampleValueAttr    int `xml:"UpdateSampleValue,attr,omitempty"`
}

// SqlTaskUpdateStatisticsTypeEnum ...
type SqlTaskUpdateStatisticsTypeEnum int

// SqlTaskUpdateScanTypeEnum ...
type SqlTaskUpdateScanTypeEnum int

// SqlTaskDataElementSqlTaskType ...
type SqlTaskDataElementSqlTaskType struct {
	SQLTaskSqlTaskBaseAttributeGroup *SqlTaskBaseAttributeGroup
}

// SqlTaskDataElementBackupTaskType ...
type SqlTaskDataElementBackupTaskType struct {
	SQLTaskSqlTaskBaseAttributeGroup         *SqlTaskBaseAttributeGroup
	SQLTaskMaintenanceTaskBaseAttributeGroup *MaintenanceTaskBaseAttributeGroup
	SQLTaskBackupTaskAttributeGroup          *BackupTaskAttributeGroup
	SelectedDatabases                        []*SelectedDatabasesType `xml:"SelectedDatabases"`
}

// SqlTaskDataElementCheckIntegrityTaskType ...
type SqlTaskDataElementCheckIntegrityTaskType struct {
	SQLTaskSqlTaskBaseAttributeGroup         *SqlTaskBaseAttributeGroup
	SQLTaskMaintenanceTaskBaseAttributeGroup *MaintenanceTaskBaseAttributeGroup
	SQLTaskCheckIntegrityTaskAttributeGroup  *CheckIntegrityTaskAttributeGroup
	DatabaseSelectionTypeAttr                *int                         `xml:"DatabaseSelectionType,attr"`
	SelectedDatabases                        []*SelectedDatabasesType     `xml:"SelectedDatabases"`
	BackupDestinationList                    []*BackupDestinationListType `xml:"BackupDestinationList"`
}

// SqlTaskDataElementAgentJobTaskType ...
type SqlTaskDataElementAgentJobTaskType struct {
	SQLTaskSqlTaskBaseAttributeGroup         *SqlTaskBaseAttributeGroup
	SQLTaskMaintenanceTaskBaseAttributeGroup *MaintenanceTaskBaseAttributeGroup
	SQLTaskAgentJobTaskAttributeGroup        *AgentJobTaskAttributeGroup
}

// SqlTaskDataElementHistoryCleanupTaskType ...
type SqlTaskDataElementHistoryCleanupTaskType struct {
	SQLTaskSqlTaskBaseAttributeGroup         *SqlTaskBaseAttributeGroup
	SQLTaskMaintenanceTaskBaseAttributeGroup *MaintenanceTaskBaseAttributeGroup
	SQLTaskHistoryCleanupTaskAttributeGroup  *HistoryCleanupTaskAttributeGroup
	RemoveOlderThanAttr                      *int `xml:"RemoveOlderThan,attr"`
	TimeUnitsTypeAttr                        *int `xml:"TimeUnitsType,attr"`
}

// SqlTaskDataElementMaintenanceFileCleanupTaskType ...
type SqlTaskDataElementMaintenanceFileCleanupTaskType struct {
	SQLTaskSqlTaskBaseAttributeGroup                *SqlTaskBaseAttributeGroup
	SQLTaskMaintenanceTaskBaseAttributeGroup        *MaintenanceTaskBaseAttributeGroup
	SQLTaskMaintenanceFileCleanupTaskAttributeGroup *MaintenanceFileCleanupTaskAttributeGroup
	RemoveOlderThanAttr                             *int `xml:"RemoveOlderThan,attr"`
	TimeUnitsTypeAttr                               *int `xml:"TimeUnitsType,attr"`
}

// SqlTaskDataElementNotifyOperatorTaskType ...
type SqlTaskDataElementNotifyOperatorTaskType struct {
	SQLTaskSqlTaskBaseAttributeGroup         *SqlTaskBaseAttributeGroup
	SQLTaskMaintenanceTaskBaseAttributeGroup *MaintenanceTaskBaseAttributeGroup
	SQLTaskNotifyOperatorTaskAttributeGroup  *NotifyOperatorTaskAttributeGroup
	OperatorNotifyList                       []*OperatorNotifyListType `xml:"OperatorNotifyList"`
}

// SqlTaskDataElementRebuildIndexTaskType ...
type SqlTaskDataElementRebuildIndexTaskType struct {
	SQLTaskSqlTaskBaseAttributeGroup         *SqlTaskBaseAttributeGroup
	SQLTaskMaintenanceTaskBaseAttributeGroup *MaintenanceTaskBaseAttributeGroup
	SQLTaskRebuildIndexTaskAttributeGroup    *RebuildIndexTaskAttributeGroup
	DatabaseSelectionTypeAttr                *int                     `xml:"DatabaseSelectionType,attr"`
	SelectedDatabases                        []*SelectedDatabasesType `xml:"SelectedDatabases"`
}

// SqlTaskDataElementReorganizeIndexTaskType ...
type SqlTaskDataElementReorganizeIndexTaskType struct {
	SQLTaskSqlTaskBaseAttributeGroup         *SqlTaskBaseAttributeGroup
	SQLTaskMaintenanceTaskBaseAttributeGroup *MaintenanceTaskBaseAttributeGroup
	SQLTaskReorganizeIndexTaskAttributeGroup *ReorganizeIndexTaskAttributeGroup
	DatabaseSelectionTypeAttr                *int                     `xml:"DatabaseSelectionType,attr"`
	SelectedDatabases                        []*SelectedDatabasesType `xml:"SelectedDatabases"`
}

// SqlTaskDataElementShrinkDatabaseTaskType ...
type SqlTaskDataElementShrinkDatabaseTaskType struct {
	SQLTaskSqlTaskBaseAttributeGroup         *SqlTaskBaseAttributeGroup
	SQLTaskMaintenanceTaskBaseAttributeGroup *MaintenanceTaskBaseAttributeGroup
	SQLTaskShrinkDBTaskAttributeGroup        *ShrinkDBTaskAttributeGroup
	DatabaseSelectionTypeAttr                *int                     `xml:"DatabaseSelectionType,attr"`
	SelectedDatabases                        []*SelectedDatabasesType `xml:"SelectedDatabases"`
}

// SqlTaskDataElementUpdateStatisticsTaskType ...
type SqlTaskDataElementUpdateStatisticsTaskType struct {
	SQLTaskSqlTaskBaseAttributeGroup          *SqlTaskBaseAttributeGroup
	SQLTaskMaintenanceTaskBaseAttributeGroup  *MaintenanceTaskBaseAttributeGroup
	SQLTaskUpdateStatisticsTaskAttributeGroup *UpdateStatisticsTaskAttributeGroup
	DatabaseSelectionTypeAttr                 *int                     `xml:"DatabaseSelectionType,attr"`
	SelectedDatabases                         []*SelectedDatabasesType `xml:"SelectedDatabases"`
}

// SqlTaskDataElementTSQLExecuteTaskType ...
type SqlTaskDataElementTSQLExecuteTaskType struct {
	SQLTaskSqlTaskBaseAttributeGroup         *SqlTaskBaseAttributeGroup
	SQLTaskMaintenanceTaskBaseAttributeGroup *MaintenanceTaskBaseAttributeGroup
}
