// Code generated by xgen. DO NOT EDIT.

package schema

// WebServiceTaskData ...
type WebServiceTaskData *WSTaskDataType

// WSTaskDataType ...
type WSTaskDataType struct {
	ConnectionNameAttr    *string                           `xml:"ConnectionName,attr"`
	ServiceAttr           *string                           `xml:"Service,attr"`
	WSDLFileAttr          *string                           `xml:"WSDLFile,attr"`
	OverwriteWSDLFileAttr *string                           `xml:"OverwriteWSDLFile,attr"`
	OutputTypeAttr        *string                           `xml:"OutputType,attr"`
	OutputLocationAttr    *string                           `xml:"OutputLocation,attr"`
	MethodInfo            *WebServiceTaskDataMethodInfoType `xml:"MethodInfo"`
}

// WebServiceTaskDataMethodInfoType ...
type WebServiceTaskDataMethodInfoType struct {
	MethodNameAttr  *string                            `xml:"MethodName,attr"`
	MessageNameAttr *string                            `xml:"MessageName,attr"`
	Documentation   *string                            `xml:"Documentation"`
	ParamInfo       []*WebServiceTaskDataParamInfoType `xml:"ParamInfo"`
}

// WebServiceTaskDataParamInfoType ...
type WebServiceTaskDataParamInfoType struct {
	NameAttr       *string        `xml:"Name,attr"`
	DatatypeAttr   *string        `xml:"Datatype,attr"`
	ParamTypeAttr  *string        `xml:"ParamType,attr"`
	SeqNumberAttr  *int           `xml:"SeqNumber,attr"`
	VariableValue  *string        `xml:"VariableValue"`
	PrimitiveValue *AnySimpleType `xml:"PrimitiveValue"`
}

// WebServiceTaskDataOutputTypeEnum ...
type WebServiceTaskDataOutputTypeEnum string

// ParamTypeEnum ...
type ParamTypeEnum string
